### ISSUE TITLE
controls bar unavailable after inline editing

### ISSUE THREAD

**Issue by omniperspective** [AndiLeni/pico_edit#2]
If I edit my page and the page has to scroll, the top control bar disappears, and can't undo this effect.
Effectively I can't save or preview anymore.

**Comment by AndiLeni** [comment]
I could not reproduce this behavior. Can you please explain it a bit more detailed?

**Comment by omniperspective** [comment]
Beste Andreas,

I can.
First a screen shot How I see it.



What I miss is:

1.
The preview and trash icons.
2.
I have about 800 small files in the content directory,
only a small amount is accessible, there is no scroll bar.

screenshot 2,
If I add a few extra blank lines in the text, the last row is available for editing.
The line "[NginxConfig]: http://picocms.org/in-depth/nginx/“ is visible.

**Comment by AndiLeni** [comment]
Due to the fact that you used the email reply function there are no screenshots available. 
Could you please retry using the github website?

**Comment by omniperspective** [comment]
Beste Andreas,

I can.
First a screen shot How I see it.
![screenshot-1](https://user-images.githubusercontent.com/18465915/27885583-c787cc98-61d8-11e7-9a18-c45e82c8c065.png)

What I miss is, and I don't understand why:
1.I have about 800 small files in the content directory, only a small amount is accessible, there is no scroll bar.

2. The preview and trash icons.
![screenshot-3](https://user-images.githubusercontent.com/18465915/27885598-cfbb36c0-61d8-11e7-8cc5-3fa9eee56a86.png)

screenshot 2,

The last line in screenshot 1 is "[ModRewrite ....]
But in the real text there is one line extra on the page.
If I add a few extra blank lines in the text, the last row is available for editing.
The line "[NginxConfig]: http://picocms.org/in-depth/nginx/“ is visible.

![screenshot-2](https://user-images.githubusercontent.com/18465915/27885546-a8353af6-61d8-11e7-83d0-b939586d559e.png)

Hope this explains my troubles.
Thanks for your help in advance
regards Henk.

**Comment by AndiLeni** [comment]
Hey,
I published some fixes. Unfortunately, I don't own a Mac so I can't test it for safari.

Regards
Andi

**Comment by omniperspective** [comment]
Beste Andi,

works like a advertised. great fix.
Works on Apple Safari.

Can close this issue as the issue is fixed

Thanks again for your help
Henk Melching

**Comment by AndiLeni** [comment]
I'm glad that I could help.

Regards
Andi
